
theme: jekyll-theme-cayman
#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: "Pixiv插图批量获取喵"
# Short bio or description (displayed in the header)
description: "多平台支持……？"

#
# Flags below are optional
#

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars.githubusercontent.com/u/169080523?v=4
# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://kdxhub.github.io/pixiv.re_ui/favicon.ico

# Text under the icons in footer
footer-text: Copyright © 2024 kdxiaoyi. All right reserved.<br><a href="https://kdx233.github.io/licen">Our License</a>

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: # fromendworld
    